
* DIALOGUE FORMAT
  A dialogue object is a dictionary. Its elements are the various
  dialogue states, whose respective names are the dictionary keys. The
  values are arrays of instructions.

  An instruction is a dictionary. Instructions always have a ~command~
  key. All of the other keys depend on which instruction is being executed.

  + ~command~ (required) - Determines the instruction to execute.
** ~say~ Instruction
   Displays text to the screen in dialogue format.
   + ~text~ (required) - The text to display.
   + ~speaker~ (optional) - The speaker.
** ~goto~ Instruction
   Unconditionally jumps to a given state.
   + ~target~ (required) - The state to go to. This state must exist,
     but its instruction list can be empty (in which case the dialogue will
     end).
** ~end~ Instruction
   Ends the conversation. It is not strictly necessary to end a state
   with this instruction, but it makes the intention more clear.
** ~branch~ Instruction
   Provides the player with a set of options.
   + ~text~ (required) - The text to display.
   + ~speaker~ (optional) - The speaker.
   + ~options~ (required) - An array of options. Each option should
     have a ~text~ key and a ~state~ key.
** ~action~ Instruction
   Performs an action in the game room.
   + ~action~ (required) - The action to perform.
   + ~arg~ (o / r) - An argument. May be required, depending on the action.
*** ~noop~ Action
    Does nothing. No argument necessary.
*** ~harm_player~ Action
    Deals damage to the player. ~arg~ is required and must be a
    nonnegative integer.
*** ~furniture_drop~ Action
    Performs the furniture drop visual effect. ~arg~ is required and
    must be a sprite resource.
*** ~meet_ghost~ Action
    Registers the fact that the player has met (and interrogated) a
    given ghost in the ghost database. Once registered, the ghost will
    show up in the player's pause menu, where he can view the clues of
    all ghosts he has met. ~arg~ is required and must be the ghost's
    string key (from the JSON file).
** ~dump_vars~ Instruction
   Prints out all of the variables currently available to the current
   dialogue in JSON form, for debugging purposes.
   + ~speaker~ (optional) - The speaker.
* ROOM FORMAT
  A room object specifies generation parameters for producing a room.
  It is a dictionary whose top-level keys are as follows. All of these
  are required. See ~room.json~.
** ~config~ (required)
   A dictionary specifying various configuration data.
*** ~width~ (required)
    Specifies the width of the room, in generator units. Must be an
    integer.
*** ~height~ (required)
    Specifies the height of the room, in generator units. Must be an
    integer.
*** ~percent_evil~ (required)
    The percentage (0.00 to 1.00) of furniture that will be turned
    vanishing and evil.
